const oldBhajansCollection = {
  "Ganesh": [
    "Pranava swaroopa pahi gajanana",
    "Ganeshwara",
    "Bhajore Bhajore Gananaadham Bhajore",
    "Gowri Ganesha Parvati Tanaya",
    "Gowri Ganesa Vinayaka",
  ],

  "Guru": [
    "Guru Sai Maheswara",
    "Dayakaro Sadguru Sai",
    "Prathah Smaranam",
    "Guruvara Naam Pavana Naam",
    "Dattaatreya Sadguru Deva",
    "Bhajore Manuva Sadguru Deva",
  ],

  "Matha": [
    "Vidya Dayini",
    "Prema mai sai maa",
    "Anthar jyothi",
    "Sarswathi saraswathi",
    "Sri kari krupa kari",
    "Jai Jai Sai Ma Hey Sai Saraswati Ma",
    "Om Jagat Janani",
    "Jaya Jagat Janani Jagadambe",
    "Simhavahini Sai Narayani",
    "Jaya Jaya Jaya Jagavandini Maa",
  ],

  "Krishna": [
    "Hey Nandalala jai Jai Gopala",
    "Madhava Murahara Murali Gopala",
    "Nandaana Krishnanaa Devaki Nandanaa",
    "Madhava Mohana",
    "Krishna Madhava madhava krishna",
    "Bhajaman shyama sundara",
    "Krishna Kanhaiya",
    "Brindavanme radhe shyam",
    "Girdihara Nagara",
    "Anupamaa sundara",
    "Madhava murahara",
    "Madhuvana murali",
    "Sapane me avo",
    "Radhika jeevana",
    "Giridhara Govinda gopala",
    "Sundara sundara sai sundara",
    "Madhava muruhara Murali Gopala",
    "Karunasagara hey nandalala",
    "Kalyana krishna",
    "Giridhari hey nandalal",
    "Muralidhara mukunda murari",
    "Vinathi Suno Vinati suno",
    "Madhava Hare krishna",
    "Sai rama sai krishna",
    "Hey Vrijbala Gopala",
    "Jai Sai Gopala Jaya Nandalala",
    "Mathuradhipathey Krishna Mukunda",
    "Sai Govinda Sai Gopala",
    "Hey Deena Dayalo Hare Sai Ram Hare Krishna",
    "Man Mandir Mein Aao Sai",
    "Radhe Shayama Hey Ghanashyama",
    "Muralidhara Hare Mohana Krishna",
    "Giridhar Mere Gopala",
    "Krishna Sri Hari Krishna",
    "Jaya Jaya Jaya Hey Madhusudhana",
    "Murali Madhura Sai Murali Madhura Krishna",
    "Giridhari Hey Nandalala",
    "Radhe Govind Bolo Tu Mukh Se",
    "Radha Madhava Madana Gopal",
    "Madhuvana Murali Syama Murari",
    "Mana Mohana Krishna Kunja Vihari",
    "Hey Nandalala Hey Vrajabala",
    "Sai Mukunda Janardhana",
    "Gopala Radhe Gopala",
    "Sri Krishna Chaitanya Prabhu Nitya",
    "Sundara Shyama Murari",
    "Meera Nath Hare Giridhari",
    "Krishna Krishna Mukunda Janardhana",
    "Jaya Jaya Prabhu Giridhari",
  ],

  "Rama": [
    "Raghupathe Raghava",
    "Raghava Sundara",
    "Manuva bolo jai seetaram bolo",
    "Raghupathi Ram Jaya jaya Ram",
    "Vaidehi priya",
    "Jagadashraya Sri Raghu Rama",
    "Bhajare Rama Charan Satatam",
    "Jaya Sai Rama Jaya Raghu Ram",
    "Sumangala Nama Suguna",
    "Darishan Deejo Dasharatha Rama",
  ],

  "Vittal / Narayana / Govind": [
    "Pranava Swarupa Hari Om",
    "Hari Gun Gaan Karo",
    "Hari nam gathe chalo",
    "Hari Narayana (3) Sai Narayana",
    "Kasthuri Tilakam Narayanam",
    "Kalyana Ranga Kamaneeya Ranga",
    "Adi Narayana Sai Narayana",
  ],

  "Sarwa Dharma": [
    "Chal Re man (3) Tu Chal",
    "Iswar alla",
    "Rama hare hari nam bolo",
    "Bhuwana bandhava",
    "Deena Dukhiyon Ke Taaran Kaaran",
    "Thuma bina praan nahi",
    "Tum Ho Shyam Ram Rahim",
    "Hey Deena Dayalo Sai Rama Ram",
  ],

  "Sai": [
    "Deena Dukhiyon Se Prem Karo",
    "Bhakta Vatsala Tero Naam",
    "Parthi Puri Mey Janam Liya",
    "Anadha Bandho Sai Prabho",
    "Mujhe Darsh Dihkhao bhagwan",
    "Tumaho Anatha Natha Bhagawan",
    "Atma Me Bas Jao Baba",
    "Sai Deva Satya Swaroopa",
    "Deena Bandhava",
    "Tujhe Namaskar Sai Baba",
    "Bhagawan Krishna Namo",
    "Eswaramba Priya Tanaya",
    "Jagadodharana Parthi Vihaarana",
    "Purnavathara Sai Guru Deva",
    "Sai Darbar Me",
    "Hey Sai Hey Sai Karuna Nidhey Sathya Sai",
    "Tere Siva Prabhu Koi Nahi Hai",
    "Akhila Jagat Ke Data Sai",
    "Kholde Mandir Dwar Sai Baba",
    "Manme Smaran Karo Sai Ram",
    "Aana Hi Padega Baba Aana Hi Padega",
    "Kamalanetra Sai",
    "Hey Ram Bhagawan",
    "Shirdi Ke Bhagavan Sai Ram",
    "Deva Devottama Dina Samrakshaka",
  ],

  "Shiva": [
    "Nacho Nacho Hey Nataraj",
    "Shambo Nachey Nataraja",
    "Nataraja Nataraja Nartana Sundara Nataraja",
    "Dama Dama Dama Dama Damaru Baaje",
    "Om Namah Shivaya Hari Om Namah Shivaya",
    "Jaya Kailasapathe Shiva Shankara",
    "Daya Karo Shiva Gangadhaari",
    "Bhavanasha puttaparthi purisha",
    "Karuna Sindho Dasharatha Nandana Parthipurisha",
    "Jaya jagadeesha Jaya Paramesha",
    "Jaya jaya Hey Jagadeesha Mahesha",
    "Sai Sundara Sundara",
    "Mangala Mangala Shirdi Pureeshwara",
    "Devadi Deva Shivaya Namah Om",
  ],

  "Rama Krishna": [
    "Rama Hare Sita Ram",
    "Sai Rama Hare Sai Krishna Hare",
  ],
};
