/*
    name: "",
    day: "",
    dateSung: "",
    startTime: "",
    singer: ''
  },*/

const sundayBhajansRawData = [
  // 28th Dec 2025 - Audio: audios/28th December.mp3
  {
    name: "Gajanana Hey Shubhanana Parama Niranjana Gajavadana",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "0:30",
    singer: "Lal",
  },
  {
    name: "Karunakaro Sai Dev",
    shruthi: { ladies: "6½P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "4:30",
    singer: "Sunitha",
  },
  {
    name: "Jaya Maa Ananda Mayi Janani",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "8:32",
    singer: "A.Srinivas",
  },
  {
    name: "Govinda Madhava Gopala Keshava (Jaya Nanda Mukunda)",
    shruthi: { gents: "2P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "12:50",
    singer: "Lavanya",
  },
  {
    name: "Ravikula Ranjana Rama Sri Rama",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "18:36",
    singer: "Shantha Krishna",
  },
  {
    name: "Namo Namo Nataraja Namo",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "23:15",
    singer: "Gayathri",
  },
  {
    name: "Radheshyama Hey Ghanashyama",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "27:36",
    singer: "G.Srinivas",
  },
  {
    name: "Satya Dharma Shanti Prema Swaroopa Prashanthi Nilaya Deva",
    shruthi: { gents: "3P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "32:30",
    singer: "Vani & Praneetha",
  },
  {
    name: "Hey Ayodhya Vasi Ram(2) Dasaratha Nandana Ram",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "36:47",
    singer: "Sridhar",
  },
  {
    name: "Subha Aur Shyam Bol Hari Naam",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "40:42",
    singer: "Vathsalya & Sai Shruthi & Harshitha",
  },
  {
    name: "Manamohana Krishna Kunja Vihari",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "43:08",
    singer: "Swaroop",
  },
  // 21st Dec 2025 - No audio file available
  {
    name: "Sri Ganapathi Hari Om",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Maata Pita Guru Bandhu Sakha",
    shruthi: { gents: "4P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Nada Brahma Nayi Sai Eshwari",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Sai Charan Sukhdaayiman",
    shruthi: { gents: "2P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Muralidhara Gopal Madhura",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Nacho Hey Nataraj shiva shambho",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Radhe Govinda Krishna Murari",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Prabhu Ramachandra Ke",
    shruthi: { gents: "3P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Hari Ananda Maya Jaya",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Mandir Mein Aao Madhava",
    shruthi: { gents: "6P", ladies: "4P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Hey Sai Jagannatha",
    shruthi: { gents: "1½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  // 30th Nov 2025 - Audio: audios/30th+Nov+2025.mp3
  {
    name: "Lambodara Hey Gowri Nandana",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "0:00",
    singer: "Karthik",
  },
  {
    name: "Satya Dharma Shanti prema Sabko Deejo",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "3:09",
    singer: "Vathsalya & Chandini & Yoshitha",
  },
  {
    name: "Maata Maheshwari Tribhuvani Janani",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "6:03",
    singer: "A.Srinivas",
  },
  {
    name: "Sita Rama Sri Raghurama",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "10:21",
    singer: "Sunitha",
  },
  {
    name: "Ghana Ghana Neela Vadana Ati Sundara",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "14:20",
    singer: "Sharath",
  },
  {
    name: "Yuga Yuga Ke Avataara Tum Hi Ho",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "18:27",
    singer: "Sahiti",
  },
  {
    name: "Tum ho Shankara Daata Sai Shankara",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "22:57",
    singer: "Abhishek",
  },
  {
    name: "Manuva Bolo Radhe(3) Shyama Naam",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "26:20",
    singer: "Eshwar",
  },
  {
    name: "Jaya Jaya Mangala Sai Namo",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "30:11",
    singer: "Sridhar",
  },
  {
    name: "Bhajo Mathura Hari Naam Nirantara",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "32:48",
    singer: "Vathsalya & Chandini & Yoshitha",
  },
  {
    name: "Nandalala(2) Nanda Mukunda Hari Nandalala",
    shruthi: { gents: "7P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "35:58",
    singer: "Sharath",
  },
  {
    name: "Aao Pyaare Nayan Hamare ",
    shruthi: { gents: "6½P", ladies: "4½P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "38:04",
    singer: "Sahiti",
  },
  {
    name: "Sharanu Ghosha Priyaney Ayyappa",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "42:00",
    singer: "G.Srinivas",
  },
  // 4th Jan 2026 - Audio: audios/4th Jan 2026.mp3
  {
    name: "Prathama Sharana Gananayaka",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "0:29",
    singer: "Lavanya",
  },
  {
    name: "Jaya Guru Omkara Sadguru Omkaara",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "3:32",
    singer: "A.Srinivas",
  },
  {
    name: "Jaya Maa Hey Sai Maa",
    shruthi: { ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "7:46",
    singer: "Sunitha",
  },
  {
    name: "Narayana Hari Narayana",
    shruthi: { gents: "2½P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "12:31",
    singer: "Abhishek",
  },
  {
    name: "Murali Krishna mukunda krishna",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "19:05",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Srirama Bhadra Sri rama chandra Sri Rama Jaya Sri Ram",
    shruthi: { gents: "1P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "22:52",
    singer: "Shantha Krishna",
  },
  {
    name: "Hari Om Namah Shivaya",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "28:02",
    singer: "Lavanya",
  },
  {
    name: "Jai(3) Manamohana Jai(3) Madhusudana",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "31:51",
    singer: "Eshwar",
  },
  {
    name: "Sitaram Nama Bhajo",
    shruthi: { gents: "7P", ladies: "4P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "34:07",
    singer: "Harshitha & Sri",
  },
  {
    name: "Shiva(2) Shambho hara(2) Shambho Sai Shambho Shankara ",
    shruthi: { gents: "3P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "36:10",
    // singers:'Rajesh'
  },
  {
    name: "Seeta Rakshaka Rama Doota",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "39:20",
    singer: "Sunitha",
  },
  {
    name: "Sri Ranga Hare Vittala Sai Ranga hare vittala",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "41:22",
    singer: "Venu",
  },
  //19th Oct 2025
  {
    name: "Neela Greeva Kumara",
    shruthi: { gents: "4P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "01:36",
    singer: "G.Srinivas",
  },
  {
    name: "Jaya Guru Shankara Girija Ramana",
    shruthi: { ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "04:19",
    singer: "Lavanya",
  },
  {
    name: "Janani Sai Devi Dayamayi",
    shruthi: { gents: "2½P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "07:25",
    singer: "Venu",
  },
  {
    name: "Ajanubahum Aravinda Netram",
    shruthi: { gents: "1½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "10:55",
    singer: "Chandini & Harshitha",
  },
  {
    name: "Chaitanya Mayi Sai",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "14:36",
    singer: "Lal",
  },
  {
    name: "Govinda Sai Krishna Govinda(2)",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "20:32",
    singer: "Vani & Yoshitha",
  },
  {
    name: "Madhura(2) hey Muralidhari",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "23:33",
    singer: "Sridhar",
  },
  {
    name: "Rama hare Sai Krishna Hare Sarvadharma Priya",
    shruthi: { gents: "2½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "26:13",
    singer: "Sai Harshitha & Ravali",
  },
  {
    name: "Jaya(2) Rama Jaya Raghurama",
    shruthi: { gents: "2P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "29:55",
    singer: "A.Srinivas",
  },
  {
    name: "Panduranga Vittala Jai Pandarinatha Vittala",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "33:55",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Shambho Murarey Shankara Murarey",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "37:13",
    singer: "Eshwar",
  },
  {
    name: "Rama Lakshmana Janaki Jai Bolo Hanuman Ki",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "39:28",
    singer: "Lavanya",
  },
  {
    name: "Meeru Meghalaya Mayurasana",
    shruthi: { gents: "5P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "43:06",
    singer: "G.Srinivas",
  },
  //31st August 2025
  {
    name: "Sri Ganapati Hari Om",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "0:00",
    singer: "A.Srinivas",
  },
  {
    name: "Sri Sai Natha Guru Govinda",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "4:31",
    singer: "Vathsalya & Sai Shruthi",
  },
  {
    name: "Devi Bhavani Jagat Janani",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "6:54",
    singer: "Sridhar",
  },
  {
    name: "Jaya Jaya Shankara Kailaasa Vaasi",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "10:35",
    singer: "Lavanya",
  },
  {
    name: "Madhuvana Sanchari Shyama Murari",
    shruthi: { gents: "6P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "14:42",
    singer: "Abhishek",
  },
  {
    name: "Jaya(2) Mangala Sai Namo",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "18:16",
    singer: "Vani & Vathsalya",
  },
  {
    name: "Shiva(2) Shankara Hara Parameshwara",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "20:58",
    singer: "Venu",
  },
  {
    name: "Hari Narayana Govinda Jaya Narayana Gopala",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "24:24",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Sri Rama Paratparara Ram Hey Rajeeva Lochana Ram",
    shruthi: { gents: "5P", ladies: "7P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "26:24",
    singer: "Eshwar",
  },
  {
    name: "Bhavasagara Se Paar Uthaaro",
    shruthi: { gents: "1½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "30:03",
    singer: "Lavanya",
  },
  {
    name: "Sai Natha Bhagawaan",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "34:21",
    singer: "Venu",
  },
  {
    name: "Vittala Vittala Sai Narayana",
    shruthi: { gents: "6½P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "38:26",
    singer: "Abhishek",
  },
  //21st September 2025 Add
  {
    name: "Namami Nityam Smarami Nityam Gajavadanam",
    day: "Sunday",
    shruthi: { gents: "4P", ladies: "1P" },
    dateSung: "2025-09-21",
    startTime: "0:00",
    singer: "Vathsalya & Sai Shruthi",
  },
  {
    name: "Aruna Ramana Sri Gurudeva",
    shruthi: { gents: "1½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "2:18",
    singer: "A.Srinivas",
  },
  {
    name: "Durga Amba Bhavani Jai Jai",
    shruthi: { gents: "2½P", ladies: "6½P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "7:18",
  },
  {
    name: "Kausalya Nandana Vaidehi Mohana",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "9:56",
    singer: "Lal",
  },
  {
    name: "Kamala Nayana Narayana",
    shruthi: { gents: "7P", ladies: "4½P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "14:32",
    singer: "Sunitha",
  },
  {
    name: "Satya Dharma Shanti Prema Swaroopa Prashanthi Nilaya Deva",
    shruthi: { gents: "4P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "16:49",
    singer: "Karthik",
  },
  {
    name: "Atma Ram Aananda Ram",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "21:22",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Madhava Madhusudana Muralidhara Mohana",
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "24:10",
    singer: "Venu",
  },
  {
    name: "Ganga Jatadhara Gowri Shankara Girija Mano Ramana",
    shruthi: { gents: "5½P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "26:22",
    singer: "Sai Harshitha & Ravali",
  },
  {
    name: "Hari Narayana Govinda Jaya Narayana Gopala",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "30:22",
    singer: "Eshwar",
  },
  {
    name: "Manamohana Nandalaal",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "32:32",
    singer: "Surekha & Praneetha",
  },
  {
    name: "Vaheguru(3)Ji Bolo",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "35:53",
    singer: "Abhishek",
  },
  {
    name: "Hey Rama Doota Hey Rama Bhakta",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "40:24",
    singer: "Yoshitha & Vani",
  },
  {
    name: "Om Shivaaya Shivaaya",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "43:15",
    singer: "Lavanya",
  },
  //11th January 2026
  {
    name: "Gajamukha Gajamukha",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "0:00",
    singer: "Abhiram",
  },
  {
    name: "Karunya Roopa Sri Sai Deva",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "3:13",
    singer: "Lavanya",
  },
  {
    name: "Jaya Devi Bhavani Maa",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "6:39",
    singer: "G.Srinivas",
  },
  {
    name: "Allah Sai Allah Maula Sai Maula",
    shruthi: { gents: "2½P", ladies: "6½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "11:40",
    singer: "Gayathri",
  },
  {
    name: "Kodanda Rama Kalyana Rama",
    shruthi: { gents: "1½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "16:26",
    singer: "Shantha Krishna",
  },
  {
    name: "Panduranga(3) Vittala",
    shruthi: { ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "20:20",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Ram(2) Bhajamana Hare Hare",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "23:40",
    singer: "Sridhar",
  },
  {
    name: "Sarvatra Govinda Namasankeerthana Govinda Haro Govinda",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "26:49",
    singer: "Vathsalya & Chandini",
  },
  {
    name: "Nandalala(2) Nanda Mukunda Hari Nandalala",
    shruthi: { gents: "1½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "29:51",
    singer: "Abhishek",
  },
  {
    name: "Jai Hari Bol Jai Sitaram",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "31:52",
    singer: "Vani & Praneetha",
  },
  {
    name: "Vanamali Vasudeva Jaganmohana Radha Ramana",
    shruthi: { gents: "6P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "35:36",
    singer: "Abhiram",
  },
  {
    name: "Shambho Shankara Parvati Ramana Pasupati Paramesha",
    shruthi: { gents: "1P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "39:20",
    singer: "Sowmya & Sri Vidya",
  },
  {
    name: "Rama Lakshmana Janaki Jai Bolo Hanuman Ki",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "41:39",
    singer: "Swaroop",
  },
  //18th Jan 2026
  {
    name: "Parvati Nandana Gajanana",
    shruthi: { gents: "5½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "0:00",
    singer: "Abhishek",
  },
  {
    name: "Gurudeva Priyadeva Saideva Dayamaya",
    shruthi: { gents: "7", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "3:32",
    singer: "Gayathri",
  },
  {
    name: "Devi Sai Maa Devi Saraswati Maa",
    shruthi: { gents: "1", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "8:52",
    singer: "Sridhar",
  },
  {
    name: "Govinda Bolo Gopala Bolo",
    shruthi: { gents: "2½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "12:45",
    singer: "A.Srinivas",
  },
  {
    name: "Tumaho Ram Tumaho Shyam",
    shruthi: { gents: "7½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "17:32",
    singer: "Sai Shruthi & Vathsalya",
  },
  {
    name: "Jaya Jaya Ram Jagadabhi Ram",
    shruthi: { gents: "2", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "20:45",
    singer: "Ganapathi",
  },
  {
    name: "Hey Partipurisha Prashanthi Vaasa Sai Murari",
    shruthi: { gents: "1½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "25:57",
    singer: "Karthik",
  },
  {
    name: "Kodanda Rama Raghava Jaya Kalyana Krishna Keshava",
    shruthi: { gents: "6", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "30:32",
    singer: "Chandini & Praneetha",
  },
  {
    name: "Hey Govinda Hey Ananda Nanda Gopala",
    shruthi: { gents: "2½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "34:38",
    singer: "Charan",
  },
  {
    name: "Rama Jai Jai Ram Sai Ram Jai Jai Ram",
    shruthi: { gents: "1½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "36:56",
    singer: "G.Srinivas",
  },
  {
    name: "Arunachala Shiva Shiva Shankara SambaShiva",
    shruthi: { gents: "4", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "40:17",
    singer: "Shantha Krishna",
  },
  {
    name: "Narayana Hari Nama Bhajore Narayana Veda Parayana",
    shruthi: { gents: "1½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "44:06",
    singer: "G.Srinivas",
  },
  //1st February 2026
  {
    name: "Amba Bhavani Shiva Shambhu Kumara",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "0:01",
    singer: "Lal",
  },
  {
    name: "Guru Dhyaaye Guru Dhyaaye",
    shruthi: { ladies: "3P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "2:13",
    singer: "Sunitha",
  },
  {
    name: "Devi Bhavani Maa Satya Sai Bhavani Maa",
    shruthi: { gents: "2½ P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "4:08",
    singer: "Karthik",
  },
  {
    name: "Hey Deena Dayala Sai Rama Ram",
    shruthi: { gents: "2P", ladies: "7P" },
    day: "sunday ",
    dateSung: "2026-02-01",
    startTime: "8:00",
    singer: "Praneetha & Vani",
  },
  {
    name: "Nache Tribhanga Krishna Murari",
    shruthi: { gents: "4P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "11:20",
    singer: "Venu",
  },
  {
    name: "Shiva(4) Shiridipurishwara Shambho Shankara",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "13:46",
    singer: "Chandini, Sri & Sai Harshitha",
  },
  {
    name: "Giridhari Murari Govinda",
    shruthi: { gents: "4P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "18:08",
    singer: "Sridhar",
  },
  {
    name: "Raghupathe Sri Ramachandra Raghava Dayanidhe",
    shruthi: { gents: "3P", ladies: "6P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "20:44",
    singer: "Abhishek",
  },
  {
    name: "Madhuvana Murali Shyama Murari",
    shruthi: { gents: "2P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "23:30",
    singer: "A.Srinivas",
  },
  {
    name: "Jayaho Nataraj",
    shruthi: { gents: "1½ P", ladies: "5P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "26:39",
    singer: "G.Srinivas",
  },
  {
    name: "Sarvadharma Priya Deva",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "29:20",
    singer: "Shantha Krishna",
  },
  {
    name: "Jaya Nandalala Jai Jai Gopala",
    shruthi: { gents: "4P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "32:00",
    singer: "Lal",
  },
  {
    name: "Rama Sai(2) Rama Sai Rama Sai Ram",
    shruthi: { gents: "1½", ladies: "5P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "33:55",
    singer: "Eshwar",
  },
  {
    name: "Hari Narayana Govinda Jaya Narayana Gopala",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "38:02",
    singers: "Geetha,Jyothi & Eshwari",
  },
  // 1st March 2026
  {
    name: "Jaya Sri Ganesha Vigna Nasha Gajanana",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "0:01",
    singer: "A.Srinivas",
  },
  {
    name: "Hare Sai(2) Sai Sai Hare(2)",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "4:30",
    singer: "Harshitha & Chandini",
  },
  {
    name: "Jaya Jaya Shankari Jaya Parameshwari",
    shruthi: { gents: "6P" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "8:15",
    singer: "Karthik",
  },
  {
    name: "Sri Sai Padam Shiva Sai Padam",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "12:47",
    singer: "Lavanya",
  },
  {
    name: "Manuva Bolo Radhe(4) Shyama Shyam",
    shruthi: { gents: "5P" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "17:22",
    singer: "Charan",
  },
  {
    name: "Dasaratha Nandana Rama Dayasagara Rama",
    shruthi: { ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "21:30",
    singer: "Praneetha & Chandini",
  },
  {
    name: "Neelakanta Mahadeva Gowri Vandana",
    shruthi: { gents: "5P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "25:56",
    singer: "Eshwar",
  },
  {
    name: "Mohana mukunda hari Giridhara Govinda hari",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "28:17",
    singer: "Gayathri",
  },
  {
    name: "Sai Rama Hey Parandhama",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "32:10",
    singer: "G.Srinivas",
  },
  {
    name: "Krishna(2) Mukunda Janardhana ",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "37:25",
    singer: "Yoshitha & Sai Shruthi",
  },
  {
    name: "Manamohana Muraligopala",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "39:28",
    singer: "Lal",
  },
  {
    name: "Shyama Komala Krishna Murari",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "41:42",
    singers: "Gayathri & Lavanya",
  },
  //8 mar 2026
  {
    name: "Parvati Tanaya Vighna Vinashaka",
    deity: "ganesha",
    speed: "slow",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "0:01",
    singer: 'A.Srinivas'
  },
  {
    name: "Hari Om Namo Shiva Shakthi Namo",
    deity: "guru",
    speed: "medium",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "5:08",
    singer: 'Vathsalya & Sai Harshitha'
  }, {
    name: "Jagadhodharini Mata Durga ",
    deity: "devi",
    speed: "slow",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "8:08",
    singer: 'G.Srinivas'
  }, {
    name: "Sai narayana (2) Mangala Naam",
    deity: "sai",
    speed: "medium",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "12:22",
    singer: 'Yoshitha & Vani'
  }, {
    name: "Antaryaami Sai",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "16:00",
    singer: 'Abhishek'
  }, {
    name: "Shiridi Sai parti sai Humko Deejo",
    deity: "sai",
    speed: "medium",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "21:48",
    singer: 'Chandini & Harshitha'
  }, {
    name: "Gopala giridhara Baala",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "26:32",
    singer: 'Eshwar'
  }, {
    name: "Jaya ho Sairam(2)",
    deity: "sarvadharma",
    speed: "speed",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "30:09",
    singer: 'Praneetha & Vani'
  }, {
    name: "Hari Om Namah Shivaya ",
    deity: "shiva",
    speed: "speed",
    shruthi: { gents: "6P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "35:18",
    singer: 'Charan'
  }, {
    name: "Ram (2) Bhajaman Hare Hare",
    deity: "rama",
    speed: "speed",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "37:50",
    singers: 'Geetha,Jyothi & Eshwari'
  }, {
    name: "Vittala Narayana",
    deity: "vittala",
    speed: "speed",
    shruthi: { gents: "", ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-03-08",
    startTime: "40:21",
    singer: 'Lavanya'
  },
  // 22 march 2206
  {
    name: "Jai (3) Gananayaka",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "0:05",
    singer: "Lavanya"
  },
  {
    name: "Gurudev (2) Satya sai Natha sadguru Dev",
    shruthi: { gents: "2P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "4:22",
    singer: "Lal"
  },
  {
    name: "Triloka Palini Jagadeeshwari",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "8:35",
    singers: "Geetha,Jyothi & Eshwari"
  },
  {
    name: "Jaya Jaya Govinda Narayana",
    shruthi: { gents: "1½ P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "11:23",
    singer: "Karthik"
  },
  {
    name: "Neela Megha Shyama Krishna",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "15:53",
    singer: "Sai Harshitha & Sri"
  },
  {
    name: "Veera Dheera Shoora Hanuman Ki Jai",
    shruthi: { gents: "2P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "19:38",
    singer: "Sridhar"
  },
  {
    name: "Eshwaramba Priya Nandana",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "23:35",
    singer: "Chandini & Praneetha"
  },
  {
    name: "Hari Nam Gathe Chalo",
    shruthi: { gents: "4P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "28:22",
    singer: "Santosh"
  },
  {
    name: "Beda Paar karo mere sai",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "33:15",
    singer: "Lavanya"
  },
  {
    name: "Namami Brahma Namami Vishnu",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "36:52",
    singer: "Lal"
  },
  {
    name: "Sri Rama Charanam (3) Bhaje",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "39:20",
    singer: "G.Srinivas"
  },
  {
    name: "Meeru Meghalaya Mayurasana",
    shruthi: { gents: "5P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-22",
    startTime: "45:31",
    singer: "Karthik"
  },
  //5th apr 2026
  {
    name: "Maha Ganapathe Gajanana",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "0:01",
    singer: 'Lavanya'
  },
  {
    name: "Gurudeva(3) Sharanam",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "3:32",
    singer: 'A.Srinivas'
  },
  {
    name: "Devi Lakshmi Mam Paahi",
    shruthi: { ladies: "7P" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "7:33",
    singer: 'Sri Vidya'
  },
  {
    name: "Govinda Gopala Jaya",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "10:08",
    singer: 'Abhishek'
  },
  {
    name: "Aananda Maya Bhagawan",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "15:06",
    singer: ''
  },
  {
    name: "Satya Sai Rama Shiva Shakthi Roopa",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "19:35",
    singer: 'Lal'
  },
  {
    name: "Nanda Kishora navaneetha Chora",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "23:15",
    singer: 'Sowmya'
  },
  {
    name: "Allah Eshwar Tumaho",
    shruthi: { gents: "2P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "25:48",
    singer: 'Karthik'
  },
  {
    name: "Dhimitha Dhim(2) Nache Bhola Naam",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "28:05",
    singer: 'Praneetha & Yoshitha'
  },
  {
    name: "Hari Narayana Govinda Jaya Narayana Gopala",
    shruthi: { gents: "5P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "31:58",
    singer: 'Eshwar'
  },
  {
    name: "Bolo Narayana Jai Jai Vittala",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "34:05",
    singer: 'Vathsalya & Sai Shruthi'
  },
  {
    name: "Apaara Mahima Gunavantha",
    shruthi: { gents: "6P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "36:44",
    singer: 'Swaroop'
  },
  {
    name: "Aanand Se Bolo Jai Baba Jai",
    shruthi: { gents: "", ladies: "" },
    day: "Sunday",
    dateSung: "2026-04-05",
    startTime: "39:30",
    singer: ''
  },
  //19th April 2026
  {
    name: "Ganapathi Om Jaya Ganapathi Om",
    shruthi: { gents: "", ladies: "7P" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: '',
  },
   {
    name: "Satya Sai Smaranam(2)",
    shruthi: { gents: "4P", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Lal',
  },
   {
    name: "Jaya Maa Hey Sai Maa",
    shruthi: { gents: "", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Sunitha',
  },
   {
    name: "Dayakaro Sai Narayana",
    shruthi: { gents: "3P", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Karthik',
  },
   {
    name: "Aao Aao Sai Pyaare",
    shruthi: { gents: "", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Lavanya',
  },
   {
    name: "Raghukula Bhushana Rajeeva Nayana",
    shruthi: { gents: "2P", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Swaroop',
  },
   {
    name: "Madhava Gopala Nanda Nandana Ghana Shyama Gopala",
    shruthi: { gents: "", ladies: "4P" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Sri Vidya & Vani',
  },
   {
    name: "Sarva Dharma Swaroopa Sai",
    shruthi: { gents: "5P", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'G.Srinivas',
  },
   {
    name: "Rama(4) Rama Naama Tarakam",
    shruthi: { gents: "", ladies: "2P" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Geetha,Jyothi & Eshwari',
  },
   {
    name: "Hey Nanda(2) Gopala Aananda(2) Gopala",
    shruthi: { gents: "5P", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Eshwar',
  },
   {
    name: "Shankaram Bhaje Shankaram Bhaje",
    shruthi: { gents: "", ladies: "4P" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Yoshitha & Vathsalya',
  },
   {
    name: "Giridhara Gopala (2)",
    shruthi: { gents: "4P", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Venu',
  },
   {
    name: "Subramanyam Sai Bolo Subramanyam Sai",
    shruthi: { gents: "4P", ladies: "" },
    day: "sunday",
    dateSung: "2026-04-19",
    startTime: "",
    singer: 'Sridhar',
  },

  
];
