/*
    name: "",
    day: "",
    dateSung: "",
    startTime: "",
    singer: ''
  },*/

const sundayBhajansRawData = [
  // 28th Dec 2025 - Audio: audios/28th December.mp3
  {
    name: "Gajanana Hey Shubhanana Parama Niranjana Gajavadana",
    deity: "ganesha",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "0:30",
    singer: "Lal",
  },
  {
    name: "Karunakaro Sai Dev",
    deity: "devi",
    shruthi: { ladies: "6½P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "4:30",
    singer: "Sunitha",
  },
  {
    name: "Jaya Maa Ananda Mayi Janani",
    deity: "devi",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "8:32",
    singer: "A.Srinivas",
  },
  {
    name: "Govinda Madhava Gopala Keshava (Jaya Nanda Mukunda)",
    deity: "krishna",
    shruthi: { gents: "2P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "12:50",
    singer: "Lavanya",
  },
  {
    name: "Ravikula Ranjana Rama Sri Rama",
    deity: "rama",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "18:36",
    singer: "Shantha Krishna",
  },
  {
    name: "Namo Namo Nataraja Namo",
    deity: "shiva",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "23:15",
    singer: "Gayathri",
  },
  {
    name: "Radheshyama Hey Ghanashyama",
    deity: "krishna",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "27:36",
    singer: "G.Srinivas",
  },
  {
    name: "Satya Dharma Shanti Prema Swaroopa Prashanthi Nilaya Deva",
    deity: "sarvadharma",
    shruthi: { gents: "3P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "32:30",
    singer: "Vani & Praneetha",
  },
  {
    name: "Hey Ayodhya Vasi Ram(2) Dasaratha Nandana Ram",
    deity: "rama",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "36:47",
    singer: "Sridhar",
  },
  {
    name: "Subha Aur Shyam Bol Hari Naam",
    deity: "sai",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "40:42",
    singer: "Vathsalya & Shruthi & Harshitha",
  },
  {
    name: "Manamohana Krishna Kunja Vihari",
    deity: "vittala",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "43:08",
    singer: "Swaroop",
  },
  // 21st Dec 2025 - No audio file available
  {
    name: "Sri Ganapathi Hari Om",
    deity: "ganesha",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Maata Pita Guru Bandhu Sakha",
    deity: "sarvadharma",
    shruthi: { gents: "4P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Nada Brahma Nayi Sai Eshwari",
    deity: "shiva",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Sai Charan Sukhdaayiman",
    deity: "sai",
    shruthi: { gents: "2P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Muralidhara Gopal Madhura",
    deity: "krishna",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Nacho Hey Nataraj shiva shambho",
    deity: "shiva",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Radhe Govinda Krishna Murari",
    deity: "krishna",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Prabhu Ramachandra Ke",
    deity: "hanuman",
    shruthi: { gents: "3P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Hari Ananda Maya Jaya",
    deity: "narayana",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Mandir Mein Aao Madhava",
    deity: "vittala",
    shruthi: { gents: "6P", ladies: "4P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Hey Sai Jagannatha",
    deity: "sai",
    shruthi: { gents: "1½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  // 30th Nov 2025 - Audio: audios/30th+Nov+2025.mp3
  {
    name: "Lambodara Hey Gowri Nandana",
    deity: "ganesha",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "0:00",
    singer: "Karthik",
  },
  {
    name: "Satya Dharma Shanti prema Sabko Deejo",
    deity: "sarvadharma",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "3:09",
    singer: "Vathsalya & Chandini & Yoshitha",
  },
  {
    name: "Maata Maheshwari Tribhuvani Janani",
    deity: "devi",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "6:03",
    singer: "A.Srinivas",
  },
  {
    name: "Sita Rama Sri Raghurama",
    deity: "rama",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "10:21",
    singer: "Sunitha",
  },
  {
    name: "Ghana Ghana Neela Vadana Ati Sundara",
    deity: "krishna",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "14:20",
    singer: "Sharath",
  },
  {
    name: "Yuga Yuga Ke Avataara Tum Hi Ho",
    deity: "sarvadharma",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "18:27",
    singer: "Sahiti",
  },
  {
    name: "Tum ho Shankara Daata Sai Shankara",
    deity: "shiva",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "22:57",
    singer: "Abhishek",
  },
  {
    name: "Manuva Bolo Radhe(3) Shyama Naam",
    deity: "vittala",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "26:20",
    singer: "Eshwar",
  },
  {
    name: "Jaya Jaya Mangala Sai Namo",
    deity: "sai",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "30:11",
    singer: "Sridhar",
  },
  {
    name: "Bhajo Mathura Hari Naam Nirantara",
    deity: "sai",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "32:48",
    singer: "Vathsalya & Chandini & Yoshitha",
  },
  {
    name: "Nandalala(2) Nanda Mukunda Hari Nandalala",
    deity: "krishna",
    shruthi: { gents: "7P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "35:58",
    singer: "Sharath",
  },
  {
    name: "Aao Pyaare Nayan Hamare ",
    deity: "sai",
    shruthi: { gents: "6½P", ladies: "4½P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "38:04",
    singer: "Sahiti",
  },
  {
    name: "Sharanu Ghosha Priyaney Ayyappa",
    deity: "subramanya",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "42:00",
    singer: "G.Srinivas",
  },
  // 4th Jan 2026 - Audio: audios/4th Jan 2026.mp3
  {
    name: "Prathama Sharana Gananayaka",
    deity: "ganesha",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "0:29",
    singer: "Lavanya",
  },
  {
    name: "Jaya Guru Omkara Sadguru Omkaara",
    deity: "sarvadharma",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "3:32",
    singer: "A.Srinivas",
  },
  {
    name: "Jaya Maa Hey Sai Maa",
    deity: "devi",
    shruthi: { ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "7:46",
    singer: "Sunitha",
  },
  {
    name: "Narayana Hari Narayana",
    deity: "narayana",
    shruthi: { gents: "2½P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "12:31",
    singer: "Abhishek",
  },
  {
    name: "Murali Krishna mukunda krishna",
    deity: "krishna",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "19:05",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Srirama Bhadra Sri rama chandra Sri Rama Jaya Sri Ram",
    deity: "rama",
    shruthi: { gents: "1P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "22:52",
    singer: "Shantha Krishna",
  },
  {
    name: "Hari Om Namah Shivaya",
    deity: "shiva",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "28:02",
    singer: "Lavanya",
  },
  {
    name: "Jai(3) Manamohana Jai(3) Madhusudana",
    deity: "krishna",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "31:51",
    singer: "Eshwar",
  },
  {
    name: "Sitaram Nama Bhajo",
    deity: "rama",
    shruthi: { gents: "7P", ladies: "4P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "34:07",
    singer: "Harshitha & Sri",
  },
  {
    name: "Shiva(2) Shambho hara(2) Shambho Sai Shambho Shankara ",
    deity: "shiva",
    shruthi: { gents: "3P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "36:10",
    // singers:'Rajesh'
  },
  {
    name: "Seeta Rakshaka Rama Doota",
    deity: "hanuman",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "39:20",
    singer: "Sunitha",
  },
  {
    name: "Sri Ranga Hare Vittala Sai Ranga hare vittala",
    deity: "vittala",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "41:22",
    singer: "Venu",
  },
  //19th Oct 2025
  {
    name: "Neela Greeva Kumara",
    deity: "ganesha",
    shruthi: { gents: "4P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "01:36",
    singer: "G.Srinivas",
  },
  {
    name: "Jaya Guru Shankara Girija Ramana",
    deity: "guru",
    shruthi: { ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "04:19",
    singer: "Lavanya",
  },
  {
    name: "Janani Sai Devi Dayamayi",
    deity: "devi",
    shruthi: { gents: "2½P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "07:25",
    singer: "Venu",
  },
  {
    name: "Ajanubahum Aravinda Netram",
    deity: "sai",
    shruthi: { gents: "1½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "10:55",
    singer: "Chandini & Harshitha",
  },
  {
    name: "Chaitanya Mayi Sai",
    deity: "sai",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "14:36",
    singer: "Lal",
  },
  {
    name: "Govinda Sai Krishna Govinda(2)",
    deity: "krishna",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "20:32",
    singer: "Vani & Yoshitha",
  },
  {
    name: "Madhura(2) hey Muralidhari",
    deity: "krishna",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "23:33",
    singer: "Sridhar",
  },
  {
    name: "Rama hare Sai Krishna Hare Sarvadharma Priya",
    deity: "sarvadharma",
    shruthi: { gents: "2½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "26:13",
    singer: "Sai Harshitha & Ravali",
  },
  {
    name: "Jaya(2) Rama Jaya Raghurama",
    deity: "rama",
    shruthi: { gents: "2P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "29:55",
    singer: "A.Srinivas",
  },
  {
    name: "Panduranga Vittala Jai Pandarinatha Vittala",
    deity: "vittala",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "33:55",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Shambho Murarey Shankara Murarey",
    deity: "shiva",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "37:13",
    singer: "Eshwar",
  },
  {
    name: "Rama Lakshmana Janaki Jai Bolo Hanuman Ki",
    deity: "hanuman",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "39:28",
    singer: "Lavanya",
  },
  {
    name: "Meeru Meghalaya Mayurasana",
    deity: "subramanya",
    shruthi: { gents: "5P" },
    day: "Sunday",
    dateSung: "2025-10-19",
    startTime: "43:06",
    singer: "G.Srinivas",
  },
  //31st August 2025
  {
    name: "Sri Ganapati Hari Om",
    deity: "ganesha",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "0:00",
    singer: "A.Srinivas",
  },
  {
    name: "Sri Sai Natha Guru Govinda",
    deity: "guru",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "4:31",
    singer: "Vathsalya & Shruthi",
  },
  {
    name: "Devi Bhavani Jagat Janani",
    deity: "devi",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "6:54",
    singer: "Sridhar",
  },
  {
    name: "Jaya Jaya Shankara Kailaasa Vaasi",
    deity: "shiva",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "10:35",
    singer: "Lavanya",
  },
  {
    name: "Madhuvana Sanchari Shyama Murari",
    deity: "krishna",
    shruthi: { gents: "6P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "14:42",
    singer: "Abhishek",
  },
  {
    name: "Jaya(2) Mangala Sai Namo",
    deity: "sai",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "18:16",
    singer: "Vani & Vathsalya",
  },
  {
    name: "Shiva(2) Shankara Hara Parameshwara",
    deity: "shiva",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "20:58",
    singer: "Venu",
  },
  {
    name: "Hari Narayana Govinda Jaya Narayana Gopala",
    deity: "narayana",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "24:24",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Sri Rama Paratparara Ram Hey Rajeeva Lochana Ram",
    deity: "rama",
    shruthi: { gents: "5P", ladies: "7P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "26:24",
    singer: "Eshwar",
  },
  {
    name: "Bhavasagara Se Paar Uthaaro",
    deity: "sarvadharma",
    shruthi: { gents: "1½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "30:03",
    singer: "Lavanya",
  },
  {
    name: "Sai Natha Bhagawaan",
    deity: "sarvadharma",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "34:21",
    singer: "Venu",
  },
  {
    name: "Vittala Vittala Sai Narayana",
    deity: "vittala",
    shruthi: { gents: "6½P" },
    day: "Sunday",
    dateSung: "2025-08-31",
    startTime: "38:26",
    singer: "Abhishek",
  },
  //21st September 2025 Add
  {
    name: "Namami Nityam Smarami Nityam Gajavadanam",
    deity: "ganesha",
    day: "Sunday",
    shruthi: { gents: "4P", ladies: "1P" },
    dateSung: "2025-09-21",
    startTime: "0:00",
    singer: "Vathsalya & Shruthi",
  },
  {
    name: "Aruna Ramana Sri Gurudeva",
    deity: "guru",
    shruthi: { gents: "1½P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "2:18",
    singer: "A.Srinivas",
  },
  {
    name: "Durga Amba Bhavani Jai Jai",
    deity: "devi",
    shruthi: { gents: "2½P", ladies: "6½P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "7:18",
  },
  {
    name: "Kausalya Nandana Vaidehi Mohana",
    deity: "rama",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "9:56",
    singer: "Lal",
  },
  {
    name: "Kamala Nayana Narayana",
    deity: "narayana",
    shruthi: { gents: "7P", ladies: "4½P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "14:32",
    singer: "Sunitha",
  },
  {
    name: "Satya Dharma Shanti Prema Swaroopa Prashanthi Nilaya Deva",
    deity: "sarvadharma",
    shruthi: { gents: "4P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "16:49",
    singer: "Karthik",
  },
  {
    name: "Atma Ram Aananda Ram",
    deity: "rama",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "21:22",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Madhava Madhusudana Muralidhara Mohana",
    deity: "krishna",
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "24:10",
    singer: "Venu",
  },
  {
    name: "Ganga Jatadhara Gowri Shankara Girija Mano Ramana",
    deity: "shiva",
    shruthi: { gents: "5½P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "26:22",
    singer: "Sai Harshitha & Ravali",
  },
  {
    name: "Hari Narayana Govinda Jaya Narayana Gopala",
    deity: "narayana",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "30:22",
    singer: "Eshwar",
  },
  {
    name: "Manamohana Nandalaal",
    deity: "krishna",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "32:32",
    singer: "Surekha & Praneetha",
  },
  {
    name: "Vaheguru(3)Ji Bolo",
    deity: "guru",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "35:53",
    singer: "Abhishek",
  },
  {
    name: "Hey Rama Doota Hey Rama Bhakta",
    deity: "hanuman",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "40:24",
    singer: "Yoshitha & Vani",
  },
  {
    name: "Om Shivaaya Shivaaya",
    deity: "shiva",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-09-21",
    startTime: "43:15",
    singer: "Lavanya",
  },
  //11th January 2026
  {
    name: "Gajamukha Gajamukha",
    deity: "ganesha",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "0:00",
    singer: "Abhiram",
  },
  {
    name: "Karunya Roopa Sri Sai Deva",
    deity: "guru",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "3:13",
    singer: "Lavanya",
  },
  {
    name: "Jaya Devi Bhavani Maa",
    deity: "devi",
    shruthi: { gents: "1½P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "6:39",
    singer: "G.Srinivas",
  },
  {
    name: "Allah Sai Allah Maula Sai Maula",
    deity: "sarvadharma",
    shruthi: { gents: "2½P", ladies: "6½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "11:40",
    singer: "Gayathri",
  },
  {
    name: "Kodanda Rama Kalyana Rama",
    deity: "rama",
    shruthi: { gents: "1½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "16:26",
    singer: "Shantha Krishna",
  },
  {
    name: "Panduranga(3) Vittala",
    deity: "vittala",
    shruthi: { ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "20:20",
    singers: "Geetha,Jyothi & Eshwari",
  },
  {
    name: "Ram(2) Bhajamana Hare Hare",
    deity: "rama",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "23:40",
    singer: "Sridhar",
  },
  {
    name: "Sarvatra Govinda Namasankeerthana Govinda Haro Govinda",
    deity: "sai",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "26:49",
    singer: "Vathsalya & Chandini",
  },
  {
    name: "Nandalala(2) Nanda Mukunda Hari Nandalala",
    deity: "krishna",
    shruthi: { gents: "1½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "29:51",
    singer: "Abhishek",
  },
  {
    name: "Jai Hari Bol Jai Sitaram",
    deity: "rama",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "31:52",
    singer: "Vani & Praneetha",
  },
  {
    name: "Vanamali Vasudeva Jaganmohana Radha Ramana",
    deity: "krishna",
    shruthi: { gents: "6P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "35:36",
    singer: "Abhiram",
  },
  {
    name: "Shambho Shankara Parvati Ramana Pasupati Paramesha",
    deity: "shiva",
    shruthi: { gents: "1P", ladies: "5½P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "39:20",
    singer: "Sowmya & Sri Vidya",
  },
  {
    name: "Rama Lakshmana Janaki Jai Bolo Hanuman Ki",
    deity: "hanuman",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-11",
    startTime: "41:39",
    singer: "Swaroop",
  },
  //18th Jan 2026
  {
    name: "Parvati Nandana Gajanana",
    deity: "ganesh",
    shruthi: { gents: "5½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "0:00",
    singer: "Abhishek",
  },
  {
    name: "Gurudeva Priyadeva Saideva Dayamaya",
    deity: "guru",
    shruthi: { gents: "7", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "3:32",
    singer: "Gayathri",
  },
  {
    name: "Devi Sai Maa Devi Saraswati Maa",
    deity: "devi",
    shruthi: { gents: "1", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "8:52",
    singer: "Sridhar",
  },
  {
    name: "Govinda Bolo Gopala Bolo",
    deity: "sarvadharma",
    shruthi: { gents: "2½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "12:45",
    singer: "A.Srinivas",
  },
  {
    name: "Tumaho Ram Tumaho Shyam",
    deity: "rama",
    shruthi: { gents: "7½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "17:32",
    singer: "Shruthi & Vathsalya",
  },
  {
    name: "Jaya Jaya Ram Jagadabhi Ram",
    deity: "rama",
    shruthi: { gents: "2", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "20:45",
    singer: "Ganapathi",
  },
  {
    name: "Hey Partipurisha Prashanthi Vaasa Sai Murari",
    deity: "sai",
    shruthi: { gents: "1½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "25:57",
    singer: "Karthik",
  },
  {
    name: "Kodanda Rama Raghava Jaya Kalyana Krishna Keshava",
    deity: "rama",
    shruthi: { gents: "6", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "30:32",
    singer: "Chandini & Praneetha",
  },
  {
    name: "Hey Govinda Hey Ananda Nanda Gopala",
    deity: "krishna",
    shruthi: { gents: "2½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "34:38",
    singer: "Charan",
  },
  {
    name: "Rama Jai Jai Ram Sai Ram Jai Jai Ram",
    deity: "rama",
    shruthi: { gents: "1½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "36:56",
    singer: "G.Srinivas",
  },
  {
    name: "Arunachala Shiva Shiva Shankara SambaShiva",
    deity: "shiva",
    shruthi: { gents: "4", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "40:17",
    singer: "Shantha Krishna",
  },
  {
    name: "Narayana Hari Nama Bhajore Narayana Veda Parayana",
    deity: "narayana",
    shruthi: { gents: "1½P", ladies: "" },
    day: "sunday",
    dateSung: "2026-01-18",
    startTime: "44:06",
    singer: "G.Srinivas",
  },
  //1st February 2026
  {
    name: "Amba Bhavani Shiva Shambhu Kumara",
    deity: "ganesha",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "0:01",
    singer: "Lal",
  },
  {
    name: "Guru Dhyaaye Guru Dhyaaye",
    deity: "guru",
    shruthi: { ladies: "3P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "2:13",
    singer: "Sunitha",
  },
  {
    name: "Devi Bhavani Maa Satya Sai Bhavani Maa",
    deity: "devi",
    shruthi: { gents: "2½ P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "4:08",
    singer: "Karthik",
  },
  {
    name: "Hey Deena Dayala Sai Rama Ram",
    deity: "rama",
    shruthi: { gents: "2P", ladies: "7P" },
    day: "sunday ",
    dateSung: "2026-02-01",
    startTime: "8:00",
    singer: "Praneetha & Vani",
  },
  {
    name: "Nache Tribhanga Krishna Murari",
    deity: "krishna",
    shruthi: { gents: "4P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "11:20",
    singer: "Venu",
  },
  {
    name: "Shiva(4) Shiridipurishwara Shambho Shankara",
    deity: "shiva",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "13:46",
    singer: "Chandini, Sri & Sai Harshitha",
  },
  {
    name: "Giridhari Murari Govinda",
    deity: "krishna",
    shruthi: { gents: "4P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "18:08",
    singer: "Sridhar",
  },
  {
    name: "Raghupathe Sri Ramachandra Raghava Dayanidhe",
    deity: "rama",
    shruthi: { gents: "3P", ladies: "6P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "20:44",
    singer: "Abhishek",
  },
  {
    name: "Madhuvana Murali Shyama Murari",
    deity: "krishna",
    shruthi: { gents: "2P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "23:30",
    singer: "A.Srinivas",
  },
  {
    name: "Jayaho Nataraj",
    deity: "nataraja",
    shruthi: { gents: "1½ P", ladies: "5P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "26:39",
    singer: "G.Srinivas",
  },
  {
    name: "Sarvadharma Priya Deva",
    deity: "sarvadharma",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "29:20",
    singer: "Shantha Krishna",
  },
  {
    name: "Jaya Nandalala Jai Jai Gopala",
    deity: "gopala",
    shruthi: { gents: "4P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "32:00",
    singer: "Lal",
  },
  {
    name: "Rama Sai(2) Rama Sai Rama Sai Ram",
    deity: "rama",
    shruthi: { gents: "1½", ladies: "5P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "33:55",
    singer: "Eshwar",
  },
  {
    name: "Hari Narayana Govinda Jaya Narayana Gopala",
    deity: "narayana",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "sunday",
    dateSung: "2026-02-01",
    startTime: "38:02",
    singers: "Geetha,Jyothi & Eshwari",
  },
  // 1st March 2026
  {
    name: "Jaya Sri Ganesha Vigna Nasha Gajanana",
    deity: "ganesha",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "A.Srinivas",
  },
  {
    name: "Hare Sai(2) Sai Sai Hare(2)",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "",
  },
  {
    name: "Jaya Jaya Shankari Jaya Parameshwari",
    deity: "devi",
    shruthi: { gents: "6P" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "Karthik",
  },
  {
    name: "Sri Sai Padam Shiva Sai Padam",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "Lavanya",
  },
  {
    name: "Manuva Bolo Radhe(4) Shyama Shyam",
    deity: "rama",
    shruthi: { gents: "5P" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "Charan",
  },
  {
    name: "Dasaratha Nandana Rama Dayasagara Rama",
    deity: "rama",
    shruthi: { ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "",
  },
  {
    name: "Neelakanta Mahadeva Gowri Vandana",
    deity: "shiva",
    shruthi: { gents: "5P", ladies: "" },
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "Eshwar",
  },
  {
    name: "Mohana mukunda hari Giridhara Govinda hari",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "Gayathri",
  },
  {
    name: "Sai Rama Hey Parandhama",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "G.Srinivas",
  },
  {
    name: "Krishna(2) Mukunda Janardhana ",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "",
  },
  {
    name: "Manamohana Muraligopala",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singer: "Lal",
  },
  {
    name: "Shyama Komala Krishna Murari",
    day: "Sunday",
    dateSung: "2026-03-01",
    startTime: "",
    singers: "Gayathri & Lavanya",
  },
  //  {
  //   name: "",
  //   deity: "",
  //   shruthi: { gents: "", ladies: "" },
  //   day: "Sunday",
  //   dateSung: "2026-03-01",
  //   startTime: "",
  //   singer: ''
  // },
];
