const sundayBhajansRawData = [
  // 28th Dec 2025 - Audio: audios/28th December.mp3
  {
    name: "Gajanana Hey Shubhanana Parama Niranjana Gajavadana",
    deity: "ganesha",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "0:30",
  },
  {
    name: "Karunakaro Sai Dev",
    deity: "devi",
    speed: "slow",
    shruthi: { ladies: "6.5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "4:30",
  },
  {
    name: "Jaya Maa Ananda Mayi Janani",
    deity: "devi",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "8:32",
  },
  {
    name: "Govinda Madhava Gopala Keshava (Jaya Nanda Mukunda)",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "5.5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "12:50",
  },
  {
    name: "Ravikula Bhanjana Rama Sri Rama",
    deity: "rama",
    speed: "slow",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "18:36",
  },
  {
    name: "Namo Namo Nataraja Namo",
    deity: "shiva",
    speed: "slow",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "23:15",
  },
  {
    name: "Radheshyama Hey Ghanashyama",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "27:36",
  },
  {
    name: "Satya Dharma Shanthi Prema Swaroopa",
    deity: "sarvadharma",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "32:30",
  },
  {
    name: "Hey Ayodhya Vasi Ram(2) Dasaratha Nandana Ram",
    deity: "rama",
    speed: "fast",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "36:47",
  },
  {
    name: "Shubha Aur Shyam Bol Hari Naam",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "40:42",
  },
  {
    name: "Manamohana Krishna Kunja Vihari",
    deity: "vittala",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
    startTime: "43:08",
  },
  // 21st Dec 2025 - No audio file available
  {
    name: "Sri Ganapathi Hari Om",
    deity: "ganesha",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Maata Pita Guru Bandhu Sakha",
    deity: "sarvadharma",
    speed: "slow",
    shruthi: { gents: "4P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Nada Brahma Nayi Sai Eshwari",
    deity: "shiva",
    speed: "medium",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Sai Charan Sukhdaayiman",
    deity: "sai",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "5.5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Muralidhara Gopal Madhura",
    deity: "krishna",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Nacho Hey Nataraj shiva shambho",
    deity: "shiva",
    speed: "medium",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Radhe Govinda Krishna Murari",
    deity: "krishna",
    speed: "medium",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Prabhu Ramachandra Ke",
    deity: "hanuman",
    speed: "fast",
    shruthi: { gents: "3P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Hari Ananda Maya Jaya",
    deity: "narayana",
    speed: "fast",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Mandir Mein Aao Madhava",
    deity: "vittala",
    speed: "slow",
    shruthi: { gents: "6P", ladies: "4P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  {
    name: "Hey Sai Jagannatha",
    deity: "sai",
    speed: "medium",
    shruthi: { gents: "1.5P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
    startTime: null,
  },
  // 30th Nov 2025 - Audio: audios/30th+Nov+2025.mp3
  {
    name: "Lambodara Hey Gowri Nandana",
    deity: "ganesha",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "0:00",
  },
  {
    name: "Satya Dharma Shanti prema Sabko Deejo",
    deity: "sarvadharma",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "3:09",
  },
  {
    name: "Maata Maheshwari Tribhuvani Janani",
    deity: "devi",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "6:03",
  },
  {
    name: "Sita Rama Sri Raghurama",
    deity: "rama",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "10:21",
  },
  {
    name: "Ghana Ghana Neela Vadana Ati Sundara",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "14:20",
  },
  {
    name: "Yuga Yuga Ke Avataara Tum Hi Ho",
    deity: "sarvadharma",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "18:27",
  },
  {
    name: "Tum ho Shankara Daata Sai Shankara",
    deity: "shiva",
    speed: "slow",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "22:57",
  },
  {
    name: "Manuva Bolo Radhe(3) Shyama Naam",
    deity: "vittala",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "26:20",
  },
  {
    name: "Jaya Jaya Mangala Sai Namo",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "30:11",
  },
  {
    name: "Bhajo Mathura Hari Naam Nirantara",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "32:48",
  },
  {
    name: "Nandalala(2) nanda mukunda hari nandalala",
    deity: "krishna",
    speed: "fast",
    shruthi: { gents: "7P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "35:58",
  },
  {
    name: "Aao Pyaare Nayan Hamare ",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "6.5P", ladies: "4.5P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "38:04",
  },
  {
    name: "Sharanu Ghosha Priyaney Ayyappa",
    deity: "subramanya",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
    startTime: "42:00",
  },
  // 4th Jan 2026 - Audio: audios/4th Jan 2026.mp3
  {
    name: "Prathama Sharana Gananayaka",
    deity: "ganesha",
    speed: "slow",
    shruthi: { gents: "1.5P", ladies: "5.5P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "0:29",
  },
  {
    name: "Jaya Guru Omkara Sadguru Omkaara",
    deity: "sarvadharma",
    speed: "slow",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "3:32",
  },
  {
    name: "Jaya Maa Hey Sai Maa",
    deity: "devi",
    speed: "slow",
    shruthi: { ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "7:46",
  },
  {
    name: "Narayana Hari Narayana",
    deity: "narayana",
    speed: "slow",
    shruthi: { gents: "2.5P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "12:31",
  },
  {
    name: "Murali Krishna mukunda krishna",
    deity: "krishna",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "19:05",
  },
  {
    name: "Srirama Bhadra Sri rama chandra Sri Rama Jaya Sri Ram",
    deity: "rama",
    speed: "slow",
    shruthi: { gents: "1P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "22:52",
  },
  {
    name: "Hari Om Namah Shivaya",
    deity: "shiva",
    speed: "slow",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "28:02",
  },
  {
    name: "Jai(3) Manamohana Jai(3) Madhusudana",
    deity: "krishna",
    speed: "fast",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "31:51",
  },
  {
    name: "Sitaram Nama Bhajo",
    deity: "rama",
    speed: "medium",
    shruthi: { gents: "7P", ladies: "4P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "34:07",
  },
  {
    name: "Shiva Shiva Shambho hara Hara Shambho Sai Shambho Shankara ",
    deity: "shiva",
    speed: "fast",
    shruthi: { gents: "3P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "36:10",
  },
  {
    name: "Seeta Rakshaka Rama Doota",
    deity: "hanuman",
    speed: "fast",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "39:20",
  },
  {
    name: "Sri Ranga Hare Vittala Sai Ranga hare vittala",
    deity: "vittala",
    speed: "fast",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2026-01-04",
    startTime: "41:22",
  },
];
