const thursdayBhajansRawData = [
  // 1st Jan 2026 - Audio: audios/01st Jan 2026.mp3
  {
    name: "Jai Ganesh (3) Deva",
    deity: "ganesha",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "0:24",
  },
  {
    name: "Man Ek Baar Hari Bol",
    deity: "narayana",
    speed: "slow",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "3:54",
  },
  {
    name: "Premaswaroopini Janani Maa",
    deity: "devi",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "7:58",
  },
  {
    name: "Shiva Shambho(2) Shiva Shambho Mahadeva",
    deity: "shiva",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "5.5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "12:42",
  },
  {
    name: "Radhe Radhe Nanda Mukunda",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "4P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "17:07",
  },
  {
    name: "Govinda Nam Bhajo Gopala Naam Bhajo",
    deity: "srinivasa",
    speed: "medium",
    shruthi: { ladies: "6.5P " },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "20:44",
  },
  {
    name: "Raghuvamsa dhama Rama Ranaranga bheema Rama",
    deity: "rama",
    speed: "slow",
    shruthi: { gents: "2.5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "23:22",
  },
  {
    name: "Sarva Dharma Swaroopa Sai",
    deity: "sarvadharma",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2.5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "28:52",
  },
  {
    name: "Mana Bangaru Parti Baba",
    deity: "sai",
    speed: "speed",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "33:15",
  },
  {
    name: "Sai Namame Brahmanandam",
    deity: "sai",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "35:40",
  },
  {
    name: "Shankara (2) Sadashiva",
    deity: "shiva",
    speed: "fast",
    shruthi: { gents: "6P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "38:46",
  },
  {
    name: "Nanda Kishora Narayana",
    deity: "narayana",
    speed: "fast",
    shruthi: { gents: "6P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "41:10",
  },
  {
    name: "Yadukula Nandana Sri Hari Madhava",
    deity: "krishna",
    speed: "fast",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "43:40",
  },
  {
    name: "Vittala Vittala Hari Vittala",
    deity: "vittala",
    speed: "fast",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "45:32",
  },
  {
    name: "Anandame Sai Bhajana",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "7P", ladies: "4P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "48:01",
  },
  {
    name: "Ram(3) parama Sumangala Ram",
    deity: "ram",
    speed: "fast",
    shruthi: { gents: "2.5P", ladies: "5.5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "51:33",
  },
  {
    name: "Sri Anjaneyam Bhaje Prasannanjaneyam Bhaje",
    deity: "hanuman",
    speed: "fast",
    shruthi: { gents: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "53:40",
  },
  {
    name: "Sai Prem Dey Shanti Dey",
    deity: "sai",
    speed: "slow",
    shruthi: { gents: "4.5P", ladies: "7P" },
    day: "Thursday",
    dateSung: "2026-01-01",
    startTime: "58:30",
  },
];
