const bhajansRawData = [
    // 1st Jan 2026
  {
    name: "Jaya Ganesh (3) Deva",
    deity: "ganesha",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Man Ek Baar Hari Bol",
    deity: "narayana",
    speed: "slow",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Premaswaroopini Janani Maa",
    deity: "devi",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Shiva Shambho(2) Shiva Shambho Mahadeva",
    deity: "shiva",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "5.5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Radhe Radhe Nanda Mukunda",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "4P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Govinda Nam Bhajo Gopala Naam Bhajo",
    deity: "srinivasa",
    speed: "medium",
    shruthi: { ladies: "6.5P " },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Raghuvamsa dhama Rama Ranaranga bheema Rama",
    deity: "rama",
    speed: "slow",
    shruthi: { gents: "2.5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Sarva Dharma Swaroopa Sai",
    deity: "sarvadharma",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2.5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Mana Bangaru Parti Baba",
    deity: "sai",
    speed: "speed",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Sai Namame Brahmanandam",
    deity: "sai",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Shankara (2) Sadashiva",
    deity: "shiva",
    speed: "fast",
    shruthi: { gents: "6P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Nanda Kishora Narayana",
    deity: "narayana",
    speed: "fast",
    shruthi: { gents: "6P", ladies: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Yadukula Nandana Sri Hari Madhava",
    deity: "krishna",
    speed: "fast",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Vittala Vittala Hari Vittala",
    deity: "vittala",
    speed: "fast",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Anandame Sai Bhajana",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "7P", ladies: "4P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Ram(3) parama Sumangala Ram",
    deity: "ram",
    speed: "fast",
    shruthi: { gents: "2.5P", ladies: "5.P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Sri Anjaneyam Bhaje Prasannanjaneyam Bhaje",
    deity: "hanuman",
    speed: "fast",
    shruthi: { gents: "2P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  {
    name: "Sai Prem Dey Shanti Dey",
    deity: "sai",
    speed: "slow",
    shruthi: { gents: "4.5P", ladies: "7P" },
    day: "Thursday",
    dateSung: "2026-01-01",
  },
  // 28th Dec 2025
  {
    name: "Gajanana Hey Shubhanana Parama Niranjana Gajavadana",
    deity: "ganesha",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Jaya Maa Ananda Mayi Janani",
    deity: "devi",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Govinda Madhava Gopala Keshava (Jaya Nanda Mukunda)",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "5.5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Ravikula Bhanjana Rama Sri Rama",
    deity: "rama",
    speed: "slow",
    shruthi: { gents: "2P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Namo Namo Nataraja Namo",
    deity: "shiva",
    speed: "slow",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Radheshyama Hey Ghanashyama",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Satya Dharma Shanthi Prema Swaroopa",
    deity: "sarvadharma",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Hey Ayodhya Vasi Ram(2) Dasaratha Nandana Ram",
    deity: "rama",
    speed: "fast",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Shubha Aur Shyam Bol Hari Naam",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  {
    name: "Manamohana Krishna Kunja Vihari",
    deity: "vittala",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-28",
  },
  // 21st Dec 2205
  {
    name: "Sri Ganapathi Hari Om",
    deity: "ganesha",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Maata Pita Guru Bandhu Sakha",
    deity: "sarvadharma",
    speed: "slow",
    shruthi: { gents: "4P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Nada Brahma Nayi Sai Eshwari",
    deity: "shiva",
    speed: "medium",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Sai Charan Sukhdaayiman",
    deity: "sai",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "5.5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Muralidhara Gopal Madhura",
    deity: "krishna",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Nacho Hey Nataraj shiva shambho",
    deity: "shiva",
    speed: "medium",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Radhe Govinda Krishna Murari",
    deity: "krishna",
    speed: "medium",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Prabhu Ramachandra Ke",
    deity: "hanuman",
    speed: "fast",
    shruthi: { gents: "3P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Hari Ananda Maya Jaya",
    deity: "narayana",
    speed: "fast",
    shruthi: { gents: "7P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Mandir Mein Aao Madhave",
    deity: "vittala",
    speed: "slow",
    shruthi: { gents: "6P", ladies: "4P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  {
    name: "Hey Sai Jagannatha",
    deity: "sai",
    speed: "medium",
    shruthi: { gents: "1.5P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-12-21",
  },
  // 30th Nov 2025
  {
    name: "Lambodara Hey Gowri Nandana",
    deity: "ganesha",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Satya Dharma Shanti prema Sabko Deejo",
    deity: "sarvadharma",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Maata Maheshwari Tribhuvani Janani",
    deity: "devi",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  //   {
  //     name: "Seeta Rama Sri Raghu Rama",
  //     deity: "rama",
  //     speed: "medium",
  //     shruthi: { gents: "1.5P", ladies: "5P" },
  //     day: "Sunday",
  //     dateSung: "2025-11-30",
  //   },
  {
    name: "Ghana Ghana Neela Vadana Ati Sundara",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Yuga Yuga Ke Avataara Tum Hi Ho",
    deity: "sarvadharma",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Tum ho Shankara Daata Sai Shankara",
    deity: "shiva",
    speed: "slow",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Manuva Bolo Radhe(3) Shyama Naam",
    deity: "vittala",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Jaya Jaya Mangala Sai Namo",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Bhajo Mathura Hari Naam Nirantara",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Nandalala(2) nanda mukunda hari nandalala",
    deity: "krishna",
    speed: "fast",
    shruthi: { gents: "7P", ladies: "2P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Aao Pyaare Nayan Hamare ",
    deity: "sai",
    speed: "fast",
    shruthi: { gents: "6.5P", ladies: "4.5P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
  {
    name: "Sharanu Ghosha Priyaney Ayyappa",
    deity: "subramanya",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Sunday",
    dateSung: "2025-11-30",
  },
//   {
//   name: "",
//   deity: "",
//   speed: "",
//   shruthi: { gents: "P", ladies: "P" },
//   day: "",
//   dateSung: "",
//   },
];

const bhajansDatabase = bhajansRawData.map((bhajan, index) => ({
  id: index + 1,
  ...bhajan,
}));
