const bhogi2026RawData = [
  {
    name: "Hari Om Namo Shiva Shakti Namo",
    deity: "shiva",
    speed: "medium",
    shruthi: { gents: "1P", ladies: "5P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "00:01",
    singer: "Vathsalya",
  },
  {
    name: "Jagadeeshwari Dayakaro Maa",
    deity: "devi",
    speed: "medium",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "03:13",
    singer: "A.Srinivas",
  },
  {
    name: "Neela Megha Shyama Krishna Gopala Krishna",
    deity: "krishna",
    speed: "slow",
    shruthi: { gents: "5P", ladies: "2P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "05:55",
    singer: "",
  },
  {
    name: "Nirupama Gunasadana Charana Neeraja Dhala Nayana",
    deity: "krishna",
    speed: "fast",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "09:10",
    singer: "Geetha Jyothi & Eshwari",
  },
  {
    name: "Gopala Radha Lola",
    deity: "krishna",
    speed: "fast",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "13:02",
    singer: "G.Srinivas",
  },
  {
    name: "Rama Hare Sai Krishna Hare Sarvadharma Priya",
    deity: "sarvadharma",
    speed: "fast",
    shruthi: { gents: "3P", ladies: "5P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "16:14",
    singer: "Lavanya",
  },
  {
    name: "Manamohana Nandalal",
    deity: "krishna",
    speed: "fast",
    shruthi: { gents: "4P", ladies: "1P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "19:04",
    // singer: "Chamundeshwari & Vathsalya"
  },
  {
    name: "Alak Niranjana Bhava Bhaya Bhanjana Narayan",
    deity: "narayan",
    speed: "fast",
    shruthi: { gents: "6P", ladies: "3P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "22:54",
    singer: "A.Srinivas",
  },
  {
    name: "Shivaya Namah Shivaya (2) Shivaya Namah Om",
    deity: "shiva",
    speed: "fast",
    shruthi: { gents: "1P", ladies: "4.5P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "25:11",
    // singer: "Vathsalya"
  },
  {
    name: "Rama(2) Sai Rama",
    deity: "rama",
    speed: "medium",
    shruthi: { gents: "6P", ladies: "2.5P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "27:18",
    singer: "",
  },
  {
    name: "Jaya Panduranga Ranga Jaya Vittala",
    deity: "panduranga",
    speed: "fast",
    shruthi: { gents: "4P", ladies: "1.5P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "30:36",
    singer: "G.Srinivas",
  },
  {
    name: "Pavanasuta Hanuman Ki Jai",
    deity: "hanuman",
    speed: "medium",
    shruthi: { gents: "2P", ladies: "6P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "32:53",
    singer: "Lavanya",
  },
  {
    name: "Sharana Mayappa Swami (2)",
    deity: "subramanya",
    speed: "fast",
    shruthi: { gents: "4P" },
    day: "Wednesday",
    dateSung: "2026-01-14",
    startTime: "36:14",
    singer: "A.Srinivas",
  },
];
